src/Entity/Calend.php
<?php

namespace App\Entity;

use App\Repository\CalendRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CalendRepository::class)
 */
class Calend
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $titre;

    /**
     * @ORM\Column(type="datetime")
     */
    private $debut;

    /**
     * @ORM\Column(type="datetime")
     */
    private $fin;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="boolean")
     */
    private $dall_days;

    /**
     * @ORM\Column(type="string", length=7)
     */
    private $bg_color;

    /**
     * @ORM\Column(type="string", length=7)
     */
    private $text_color;

    /**
     * @ORM\Column(type="string", length=7)
     */
    private $border_color;

    /**
     * @ORM\ManyToOne(targetEntity=Cours::class,inversedBy="calends")
     */
    private $id_cours;

    /**
     * @ORM\ManyToOne(targetEntity=Enseignant::class, inversedBy="calends")
     */
    private $id_Enseignant;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getDebut(): ?\DateTimeInterface
    {
        return $this->debut;
    }

    public function setDebut(\DateTimeInterface $debut): self
    {
        $this->debut = $debut;

        return $this;
    }

    public function getFin(): ?\DateTimeInterface
    {
        return $this->fin;
    }

    public function setFin(\DateTimeInterface $fin): self
    {
        $this->fin = $fin;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getDallDays(): ?bool
    {
        return $this->dall_days;
    }

    public function setDallDays(bool $dall_days): self
    {
        $this->dall_days = $dall_days;

        return $this;
    }

    public function getBgColor(): ?string
    {
        return $this->bg_color;
    }

    public function setBgColor(string $bg_color): self
    {
        $this->bg_color = $bg_color;

        return $this;
    }

    public function getTextColor(): ?string
    {
        return $this->text_color;
    }

    public function setTextColor(string $text_color): self
    {
        $this->text_color = $text_color;

        return $this;
    }

    public function getBorderColor(): ?string
    {
        return $this->border_color;
    }

    public function setBorderColor(string $border_color): self
    {
        $this->border_color = $border_color;

        return $this;
    }

    public function getIdCours(): ?Cours
    {
        return $this->id_cours;
    }

    public function setIdCours(?Cours $id_cours): self
    {
        $this->id_cours = $id_cours;

        return $this;
    }

    public function getIdEnseignant(): ?Enseignant
    {
        return $this->id_Enseignant;
    }

    public function setIdEnseignant(?Enseignant $id_Enseignant): self
    {
        $this->id_Enseignant = $id_Enseignant;

        return $this;
    }
}

src/Controller/CalenderController.php
<?php

namespace App\Controller;

use App\Entity\Calend;
use App\Form\CalendType;
use App\Repository\CalendRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/calender")
 */
class CalenderController extends AbstractController
{
    /**
     * @Route("/", name="calender_index", methods={"GET"})
     */
    public function index(CalendRepository $calendRepository): Response
    {
        return $this->render('calender/index.html.twig', [
            'calends' => $calendRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="calender_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $calend = new Calend();
        $form = $this->createForm(CalendType::class, $calend);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($calend);
            $entityManager->flush();

            return $this->redirectToRoute('calender_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('calender/new.html.twig', [
            'calend' => $calend,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="calender_show", methods={"GET"})
     */
    public function show(Calend $calend): Response
    {
        return $this->render('calender/show.html.twig', [
            'calend' => $calend,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="calender_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Calend $calend): Response
    {
        $form = $this->createForm(CalendType::class, $calend);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('calender_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('calender/edit.html.twig', [
            'calend' => $calend,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="calender_delete", methods={"POST"})
     */
    public function delete(Request $request, Calend $calend): Response
    {
        if ($this->isCsrfTokenValid('delete'.$calend->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($calend);
            $entityManager->flush();
        }
        return $this->redirectToRoute('calender_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/calender/_delete_form.html.twig
<form method="post" action="{{ path('calender_delete', {'id': calend.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ calend.id) }}">
    <button class="btn">Delete</button>
</form>

templates/calender/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/calender/edit.html.twig
{% block title %}Edit Calend{% endblock %}

{% block body %}
    <h1>Edit Calend</h1>

    {{ include('calender/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('calender_index') }}">back to list</a>

    {{ include('calender/_delete_form.html.twig') }}
{% endblock %}

templates/calender/index.html.twig
{% block title %}Calend index{% endblock %}

{% block body %}
    <h1>Calend index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Titre</th>
                <th>Debut</th>
                <th>Fin</th>
                <th>Description</th>
                <th>Dall_days</th>
                <th>Bg_color</th>
                <th>Text_color</th>
                <th>Border_color</th>
                <th>Cours</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for calend in calends %}
            <tr>
                <td>{{ calend.id }}</td>
                <td>{{ calend.titre }}</td>
                <td>{{ calend.debut ? calend.debut|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ calend.fin ? calend.fin|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ calend.description }}</td>
                <td>{{ calend.dallDays ? 'Yes' : 'No' }}</td>
                <td>{{ calend.bgColor }}</td>
                <td>{{ calend.textColor }}</td>
                <td>{{ calend.borderColor }}</td>
                <td>{{ calend.idCours}}</td>
                <td>
                    <a href="{{ path('calender_show', {'id': calend.id}) }}">show</a>
                    <a href="{{ path('calender_edit', {'id': calend.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="10">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('calender_new') }}">Create new</a>
{% endblock %}

templates/calender/new.html.twig
{% block title %}New Calend{% endblock %}

{% block body %}
    <h1>Create new Calend</h1>

    {{ include('calender/_form.html.twig') }}

    <a href="{{ path('calender_index') }}">back to list</a>
{% endblock %}

templates/calender/show.html.twig
{% block title %}Calend{% endblock %}

{% block body %}
    <h1>Calend</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ calend.id }}</td>
            </tr>
            <tr>
                <th>Titre</th>
                <td>{{ calend.titre }}</td>
            </tr>
            <tr>
                <th>Debut</th>
                <td>{{ calend.debut ? calend.debut|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Fin</th>
                <td>{{ calend.fin ? calend.fin|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ calend.description }}</td>
            </tr>
            <tr>
                <th>Dall_days</th>
                <td>{{ calend.dallDays ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Bg_color</th>
                <td>{{ calend.bgColor }}</td>
            </tr>
            <tr>
                <th>Text_color</th>
                <td>{{ calend.textColor }}</td>
            </tr>
            <tr>
                <th>Border_color</th>
                <td>{{ calend.borderColor }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('calender_index') }}">back to list</a>

    <a href="{{ path('calender_edit', {'id': calend.id}) }}">edit</a>

    {{ include('calender/_delete_form.html.twig') }}
{% endblock %}